### ISSUE TITLE
Buildpack fails

### ISSUE THREAD

**Issue by ajallooeian** [swisscom/kibana-buildpack#3]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

{
   "name": "",
   "build": "",
   "support": "https://developer.swisscom.com/contact",
   "version": 0,
   "description": "Cloud Foundry provided by Swisscom",
   "authorization_endpoint": "https://login.scapp-console.swisscom.com",
   "token_endpoint": "https://uaa.scapp-console.swisscom.com",
   "min_cli_version": "6.32.0",
   "min_recommended_cli_version": "latest",
   "app_ssh_endpoint": "ssh.scapp-console.swisscom.com:2222",
   "app_ssh_host_key_fingerprint": "f2:9a:da:7f:8f:25:d2:18:90:32:aa:5f:4e:39:6b:eb",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.scapp-console.swisscom.com:443",
   "api_version": "2.124.0",
   "osbapi_version": "2.14",
   "routing_endpoint": "https://api.scapp-console.swisscom.com/routing",
   "user": "263af4c2-93e5-4256-aa9c-186323aa3328"
}
cf version 6.38.0+7ddf0aadd.2018-08-07

What version of the buildpack you are using?
default / latest

If you were attempting to accomplish a task, what was it you were attempting to do?

I am trying to push kibana to iapc, and this is what happens:

Downloading app package...
Downloaded app package (656B)
-----> Download go 1.9
-----> Running go build supply
-----> Kibana Buildpack version 6.1.3
       **ERROR** Unable to evaluate Kibana file: open /tmp/app/Kibana: no such file or directory
Failed to compile droplet: Failed to run all supply scripts: exit status 16
Exit status 223
Cell 216cfffb-8268-4518-b8ea-46f9a135fe51 stopping instance f85090f7-ff48-400e-ac21-1ff2ec8b86ab
Cell 216cfffb-8268-4518-b8ea-46f9a135fe51 destroying container for instance f85090f7-ff48-400e-ac21-1ff2ec8b86ab
Cell 216cfffb-8268-4518-b8ea-46f9a135fe51 successfully destroyed container for instance f85090f7-ff48-400e-ac21-1ff2ec8b86ab

FAILED
Error restarting application: BuildpackCompileFailed

What did you expect to happen?
This was working before, and not anymore

What was the actual behavior?

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by Lafunamor** [comment]
It seems that you're no providing a file named `Kibana` in the root directory of the application.
Please be aware that this buildpack is just one way of pushing a Kibana application to Cloud Foundry. You could also use the official Docker image.

**Comment by r-chris** [comment]
Hi @Lafunamor - since this repository has now been deprecated with the notice to please use an official Docker image, it would be very helpful to receive a general guideline as to what the recommended config for this could look like. I have read the official documentation on the elastic website, but it's insufficient in my opinion. Could you kindly share an example `manifest.yml` as a guideline. I got this far, but was still not successful in getting Kibana up and running with the swisscom Elasticsearch Service.

```yml
---
applications:
- name: kibana-test-example
  docker:
    image: docker.elastic.co/kibana/kibana:6.1.4
  memory: 4G
  disk_quota: 5G
  services:
    - elasticsearch-test-service
  env:
    SERVER_NAME: kibana-test
    # ELASTICSEARCH_HOSTS: https://abcdefghijk.elasticsearch.lyra-836.appcloud.swisscom.com
    ELASTICSEARCH_URL: https://abcdefghijk.elasticsearch.lyra-836.appcloud.swisscom.com
    ELASTICSEARCH_USERNAME: username_provided_by_elasticsearch_service
    ELASTICSEARCH_PASSWORD: password_provided_by_elasticsearch_service
    XPACK_MONITORING_ENABLED: true
```

This allows me to see the Kibana login page, but it produces errors in the log (`Error: Failed Authentication ...`) and the login page is actually disabled.

I am wondering what setup is missing to get the official docker image to work here?
